@host=localhost
@port=5258
@path=api/Analises
@query = c713b416-8c0b-4cd1-9d3c-9e3235b39871
@PiscinaPerfeita.Api_HostAddress=http://{{host}}:{{port}}/{{path}}

@piscinaId = 97d00fb5-d9be-4242-b6b3-d36dd235a5ad
@ph = 7.0
@cloro = 7.2
@alcalinidade = 110
@temp = 30.9
@obs = Tudo certo, graças a Deus!

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdm9qZXF1aXRpYmFAZW1haWwuY29tIiwicm9sZSI6IkFkbWluIiwidW5pcXVlX25hbWUiOiJOb3ZvIFRlc3RlIEplcXVpdGliYSIsIm5iZiI6MTc4MjYwMTcyNywiZXhwIjoxNzgyNjMwNTI3LCJpYXQiOjE3ODI2MDE3MjcsImlzcyI6IlBpc2NpbmFQZXJmZWl0YSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTI1OCJ9.3x0ZcbDeqUdwwxQCoMwAKqmLmur4fFzR3aVdWNFeyvs
  


GET {{PiscinaPerfeita.Api_HostAddress}}/
Accept: application/json
Authorization: Bearer {{token}}
###

GET {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Accept: application/json
Authorization: Bearer {{token}}
###

POST {{PiscinaPerfeita.Api_HostAddress}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "PiscinaId": "{{piscinaId}}",
  "Ph": {{ph}},
  "CloroLivre": {{cloro}},
  "Alcalinidade": {{alcalinidade}},
  "Temperatura": {{temp}},
  "Observacoes": "{{obs}}"
}
###

PUT {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "PiscinaId": "{{piscinaId}}",
  "Ph": {ph},
  "CloroLivre": {{cloro}},
  "Alcalinidade": {{alcalinidade}},
  "Temperatura": {{temp}},
  "Observacao": "{{obs}}"
}
###

DELETE {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Authorization: Bearer {{token}}
###