@host=localhost
@port=5258
@path=api/Analises
@query = c713b416-8c0b-4cd1-9d3c-9e3235b39871
@PiscinaPerfeita.Api_HostAddress=http://{{host}}:{{port}}/{{path}}

@piscinaId = 97d00fb5-d9be-4242-b6b3-d36dd235a5ad
@ph = 7.0
@cloro = 7.2
@alcalinidade = 110
@temp = 30.9
@obs = Tudo certo, graças a Deus!


GET {{PiscinaPerfeita.Api_HostAddress}}/
Accept: application/json
###

GET {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Accept: application/json
###

POST {{PiscinaPerfeita.Api_HostAddress}}
Content-Type: application/json
Accept: application/json

{
  "PiscinaId": "{{piscinaId}}",
  "Ph": {{ph}},
  "CloroLivre": {{cloro}},
  "Alcalinidade": {{alcalinidade}},
  "Temperatura": {{temp}},
  "Observacoes": "{{obs}}"
}
###

PUT {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Accept: application/json
Content-Type: application/json
{
  "PiscinaId": "{{piscinaId}}",
  "Ph": {ph},
  "CloroLivre": {{cloro}},
  "Alcalinidade": {{alcalinidade}},
  "Temperatura": {{temp}},
  "Observacao": "{{obs}}"
}
###

DELETE {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
###