@host=localhost
@port=5258
@path=api/Produtos
@query = 1d1b7e36-9f9d-41d6-838a-7e7dd15cd68a
@PiscinaPerfeita.Api_HostAddress=http://{{host}}:{{port}}/{{path}}

@nome = PH
@undMedida = ML

// Token Jwt
@token


GET {{PiscinaPerfeita.Api_HostAddress}}/
Accept: application/json
###

GET {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Accept: application/json
Authorization: Bearer {{token}}
###

POST {{PiscinaPerfeita.Api_HostAddress}}
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json

{
  "Nome": "{{nome}}",
  "UnidadeMedida": "{{undMedida}}"
}
###

PUT {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Nome": "{{nome}}",
  "UnidadeMedida": "{{undMedida}}"
}
###

DELETE {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Authorization: Bearer {{token}}
###