@host=localhost
@port=5258
@path=api/Usuarios
@PiscinaPerfeita.Api_HostAddress=http://{{host}}:{{port}}/{{path}}


GET {{PiscinaPerfeita.Api_HostAddress}}/
Accept: application/json
###

GET {{PiscinaPerfeita.Api_HostAddress}}/4892fb54-5e8b-4eb0-8293-7d5dc911ae7d
Accept: application/json
###

POST {{PiscinaPerfeita.Api_HostAddress}}
Content-Type: application/json
Accept: application/json

{
  "Nome": "Vinicius Oliveira",
  "Email": "vinicius@mail.com",
  "SenhaHash": "123asd"
}
###

PUT {{PiscinaPerfeita.Api_HostAddress}}/ed880ca1-e74a-4c16-8791-a9f8da0a2efa
Accept: application/json
Content-Type: application/json
{
  "Nome": "Shay Rodrigues Gomes Souza",
  "Email": "novoemail@mail.com.br",
  "SenhaHash": "123asd"
}
###

DELETE {{PiscinaPerfeita.Api_HostAddress}}/4892fb54-5e8b-4eb0-8293-7d5dc911ae7d
Accept: application/json
###