@host=localhost
@port=5258
@path=api/Usuarios
@PiscinaPerfeita.Api_HostAddress=http://{{host}}:{{port}}/{{path}}


GET {{PiscinaPerfeita.Api_HostAddress}}/
Accept: application/json
###

GET {{PiscinaPerfeita.Api_HostAddress}}/4892fb54-5e8b-4eb0-8293-7d5dc911ae7d
Accept: application/json
###

POST {{PiscinaPerfeita.Api_HostAddress}}
Content-Type: application/json
Accept: application/json

{
  "Nome": "Vinicius Oliveira",
  "Email": "vinicius@mail.com",
  "SenhaHash": "123asd"
}
###

PUT {{PiscinaPerfeita.Api_HostAddress}}/d89d2bba-7c91-4a34-a51c-7486e2e6bbcc
Accept: application/json
Content-Type: application/json
{
  "Nome": "Shay Rodrigues Gomes Souza",
  "Email": "novoemail@mail.com.br",
  "SenhaHash": "123asd"
}
###

DELETE {{PiscinaPerfeita.Api_HostAddress}}/16c61e28-2613-4f73-b0e7-131331812432
Accept: application/json
###