// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PiscinaPerfeita.Api.Data;

#nullable disable

namespace PiscinaPerfeita.Api.Migrations
{
    [DbContext(typeof(PiscinaPerfeitaContext))]
    [Migration("20260715020001_AddEstoqueIdeal")]
    partial class AddEstoqueIdeal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "piscina-perfeita", "tipo_revestimento_enum", new[] { "Vinil", "Alvenaria", "Fibra de vidro", "Pastilhas", "Porcelanato/Ceramica", "Pedras naturais" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "piscina-perfeita", "tipo_tratamento_enum", new[] { "Quimico tradicional", "Salinizacao", "Ozonio", "Luz ultravioleta" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Analise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Alcalinidade")
                        .HasColumnType("numeric")
                        .HasColumnName("alcalinidade");

                    b.Property<decimal?>("CloroLivre")
                        .HasColumnType("numeric")
                        .HasColumnName("clorolivre");

                    b.Property<DateTimeOffset>("DataAnalise")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataanalise");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("localid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("Ph")
                        .HasColumnType("numeric")
                        .HasColumnName("ph");

                    b.Property<Guid>("PiscinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("piscinaid");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("numeric")
                        .HasColumnName("temperatura");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id")
                        .HasName("pk_analises");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_analises_localid");

                    b.HasIndex("PiscinaId")
                        .HasDatabaseName("ix_analises_piscinaid");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_analises_usuarioid");

                    b.ToTable("Analises", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.AplicacaoProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AnaliseId")
                        .HasColumnType("uuid")
                        .HasColumnName("analiseid");

                    b.Property<DateTimeOffset>("DataAplicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataaplicacao");

                    b.Property<Guid>("DepositoId")
                        .HasColumnType("uuid")
                        .HasColumnName("depositoid");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("localid");

                    b.Property<Guid?>("MovimentacaoEstoqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("movimentacaoestoqueid");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PiscinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("piscinaid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produtoid");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantidade");

                    b.Property<string>("UnidadeLancamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unidadelancamento");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id")
                        .HasName("pk_aplicacoesproduto");

                    b.HasIndex("AnaliseId")
                        .HasDatabaseName("ix_aplicacoesproduto_analiseid");

                    b.HasIndex("DepositoId")
                        .HasDatabaseName("ix_aplicacoesproduto_depositoid");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_aplicacoesproduto_localid");

                    b.HasIndex("MovimentacaoEstoqueId")
                        .HasDatabaseName("ix_aplicacoesproduto_movimentacaoestoqueid");

                    b.HasIndex("PiscinaId")
                        .HasDatabaseName("ix_aplicacoesproduto_piscinaid");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_aplicacoesproduto_produtoid");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_aplicacoesproduto_usuarioid");

                    b.ToTable("AplicacoesProduto", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Deposito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("localid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.HasKey("Id")
                        .HasName("pk_depositos");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_depositos_localid");

                    b.ToTable("Depositos", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DepositoId")
                        .HasColumnType("uuid")
                        .HasColumnName("depositoid");

                    b.Property<decimal?>("EstoqueIdeal")
                        .HasColumnType("numeric")
                        .HasColumnName("estoqueideal");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("localid");

                    b.Property<Guid?>("PiscinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("piscinaid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produtoid");

                    b.Property<decimal?>("QuantidadeAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidadeatual");

                    b.Property<decimal?>("QuantidadeMinima")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidademinima");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id")
                        .HasName("pk_estoques");

                    b.HasIndex("DepositoId")
                        .HasDatabaseName("ix_estoques_depositoid");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_estoques_localid");

                    b.HasIndex("PiscinaId")
                        .HasDatabaseName("ix_estoques_piscinaid");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_estoques_produtoid");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_estoques_usuarioid");

                    b.ToTable("Estoques", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Local", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createtat");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_locais");

                    b.ToTable("Locais", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datamovimentacao");

                    b.Property<Guid>("DepositoId")
                        .HasColumnType("uuid")
                        .HasColumnName("depositoid");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("localid");

                    b.Property<Guid?>("PiscinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("piscinaid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produtoid");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("integer")
                        .HasColumnName("tipomovimentacao");

                    b.Property<string>("UnidadeLancamento")
                        .HasColumnType("text")
                        .HasColumnName("unidadelancamento");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes");

                    b.HasIndex("DepositoId")
                        .HasDatabaseName("ix_movimentacoes_depositoid");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_movimentacoes_localid");

                    b.HasIndex("PiscinaId")
                        .HasDatabaseName("ix_movimentacoes_piscinaid");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_movimentacoes_produtoid");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimentacoes_usuarioid");

                    b.ToTable("Movimentacoes", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Piscina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("localid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal?>("ProfundidadeMedia")
                        .HasColumnType("numeric")
                        .HasColumnName("profundidademedia");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.Property<decimal?>("VolumeLitros")
                        .HasColumnType("numeric")
                        .HasColumnName("volumelitros");

                    b.HasKey("Id")
                        .HasName("pk_piscinas");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_piscinas_localid");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_piscinas_usuarioid");

                    b.ToTable("Piscinas", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text")
                        .HasColumnName("fabricante");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("localid");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unidademedida");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_produtos_localid");

                    b.ToTable("Produtos", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createtat");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid?>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("localid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<Guid?>("UltimoLocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("ultimolocalid");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_usuarios_localid");

                    b.ToTable("Usuarios", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.UsuarioLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createtat");

                    b.Property<Guid?>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("localid");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id")
                        .HasName("pk_usuarioslocal");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_usuarioslocal_localid");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_usuarioslocal_usuarioid");

                    b.ToTable("UsuariosLocal", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Analise", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analises_locais_localid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", "Piscina")
                        .WithMany("Analises")
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analises_piscinas_piscinaid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analises_usuarios_usuarioid");

                    b.Navigation("Local");

                    b.Navigation("Piscina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.AplicacaoProduto", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Analise", "Analise")
                        .WithMany()
                        .HasForeignKey("AnaliseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_aplicacoesproduto_analises_analiseid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Deposito", "Deposito")
                        .WithMany()
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoesproduto_depositos_depositoid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoesproduto_locais_localid");

                    b.HasOne("PiscinaPerfeita.Api.Models.MovimentacaoEstoque", "MovimentacaoEstoque")
                        .WithMany()
                        .HasForeignKey("MovimentacaoEstoqueId")
                        .HasConstraintName("fk_aplicacoesproduto_movimentacoesestoque_movimentacaoestoqueid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", "Piscina")
                        .WithMany()
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoesproduto_piscinas_piscinaid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoesproduto_produtos_produtoid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoesproduto_usuarios_usuarioid");

                    b.Navigation("Analise");

                    b.Navigation("Deposito");

                    b.Navigation("Local");

                    b.Navigation("MovimentacaoEstoque");

                    b.Navigation("Piscina");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Deposito", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_depositos_locais_localid");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Estoque", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Deposito", "Deposito")
                        .WithMany()
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoques_depositos_depositoid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoques_locais_localid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", null)
                        .WithMany("Estoques")
                        .HasForeignKey("PiscinaId")
                        .HasConstraintName("fk_estoques_piscinas_piscinaid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoques_produtos_produtoid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoques_usuarios_usuarioid");

                    b.Navigation("Deposito");

                    b.Navigation("Local");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Deposito", "Deposito")
                        .WithMany()
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_depositos_depositoid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_locais_localid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", "Piscina")
                        .WithMany("MovimentacoesEstoques")
                        .HasForeignKey("PiscinaId")
                        .HasConstraintName("fk_movimentacoes_piscinas_piscinaid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Produto", "Produto")
                        .WithMany("MovimentacoesEstoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_produtos_produtoid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_usuarios_usuarioid");

                    b.Navigation("Deposito");

                    b.Navigation("Local");

                    b.Navigation("Piscina");

                    b.Navigation("Produto");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Piscina", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_piscinas_locais_localid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuario")
                        .WithMany("Piscinas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_piscinas_usuarios_usuarioid");

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Produto", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_locais_localid");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Usuario", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .HasConstraintName("fk_usuarios_locais_localid");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.UsuarioLocal", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .HasConstraintName("fk_usuarioslocal_locais_localid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarioslocal_usuarios_usuarioid");

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Piscina", b =>
                {
                    b.Navigation("Analises");

                    b.Navigation("Estoques");

                    b.Navigation("MovimentacoesEstoques");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Produto", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("MovimentacoesEstoques");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Usuario", b =>
                {
                    b.Navigation("Piscinas");
                });
#pragma warning restore 612, 618
        }
    }
}
