// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PiscinaPerfeita.Api.Data;

#nullable disable

namespace PiscinaPerfeita.Api.Migrations
{
    [DbContext(typeof(PiscinaPerfeitaContext))]
    [Migration("20260702030803_RenameMovimentacoesEstoque")]
    partial class RenameMovimentacoesEstoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "piscina-perfeita", "tipo_revestimento_enum", new[] { "Vinil", "Alvenaria", "Fibra de vidro", "Pastilhas", "Porcelanato/Ceramica", "Pedras naturais" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "piscina-perfeita", "tipo_tratamento_enum", new[] { "Quimico tradicional", "Salinizacao", "Ozonio", "Luz ultravioleta" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Analise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Alcalinidade")
                        .HasColumnType("numeric")
                        .HasColumnName("alcalinidade");

                    b.Property<decimal?>("CloroLivre")
                        .HasColumnType("numeric")
                        .HasColumnName("clorolivre");

                    b.Property<DateTimeOffset>("DataAnalise")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataanalise");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("Ph")
                        .HasColumnType("numeric")
                        .HasColumnName("ph");

                    b.Property<Guid>("PiscinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("piscinaid");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("numeric")
                        .HasColumnName("temperatura");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id")
                        .HasName("pk_analises");

                    b.HasIndex("PiscinaId")
                        .HasDatabaseName("ix_analises_piscinaid");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_analises_usuarioid");

                    b.ToTable("Analises", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("PiscinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("piscinaid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produtoid");

                    b.Property<decimal?>("QuantidadeAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidadeatual");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id")
                        .HasName("pk_estoques");

                    b.HasIndex("PiscinaId")
                        .HasDatabaseName("ix_estoques_piscinaid");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_estoques_produtoid");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_estoques_usuarioid");

                    b.ToTable("Estoques", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datamovimentacao");

                    b.Property<Guid>("PiscinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("piscinaid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produtoid");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("integer")
                        .HasColumnName("tipomovimentacao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes");

                    b.HasIndex("PiscinaId")
                        .HasDatabaseName("ix_movimentacoes_piscinaid");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_movimentacoes_produtoid");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimentacoes_usuarioid");

                    b.ToTable("Movimentacoes", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Piscina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal?>("ProfundidadeMedia")
                        .HasColumnType("numeric")
                        .HasColumnName("profundidademedia");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.Property<decimal?>("VolumeLitros")
                        .HasColumnType("numeric")
                        .HasColumnName("volumelitros");

                    b.HasKey("Id")
                        .HasName("pk_piscinas");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_piscinas_usuarioid");

                    b.ToTable("Piscinas", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unidademedida");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.ToTable("Produtos", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createtat");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.ToTable("Usuarios", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Analise", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", "Piscina")
                        .WithMany("Analises")
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analises_piscinas_piscinaid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analises_usuarios_usuarioid");

                    b.Navigation("Piscina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Estoque", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", "Piscina")
                        .WithMany("Estoques")
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoques_piscinas_piscinaid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoques_produtos_produtoid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoques_usuarios_usuarioid");

                    b.Navigation("Piscina");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", "Piscina")
                        .WithMany("MovimentacoesEstoques")
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_piscinas_piscinaid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Produto", "Produto")
                        .WithMany("MovimentacoesEstoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_produtos_produtoid");

                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_usuarios_usuarioid");

                    b.Navigation("Piscina");

                    b.Navigation("Produto");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Piscina", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuario")
                        .WithMany("Piscinas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_piscinas_usuarios_usuarioid");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Piscina", b =>
                {
                    b.Navigation("Analises");

                    b.Navigation("Estoques");

                    b.Navigation("MovimentacoesEstoques");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Produto", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("MovimentacoesEstoques");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Usuario", b =>
                {
                    b.Navigation("Piscinas");
                });
#pragma warning restore 612, 618
        }
    }
}
