@host=localhost
@port=5258
@path=api/Usuarios
@query=5b053622-05fe-4648-ba8f-a4de12aaa663
@PiscinaPerfeita.Api_HostAddress=http://{{host}}:{{port}}/{{path}}

@nome = Vinicius Oliveira
@email = admin@teste.com.br
@senha = 123456789
@role = 0

// Token JWT
@token 

###
GET {{PiscinaPerfeita.Api_HostAddress}}/
Accept: application/json


###

GET {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Accept: application/json

###

POST {{PiscinaPerfeita.Api_HostAddress}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


{
  "Nome": "{{nome}}",
  "Email": "{{email}}",
  "SenhaHash": "{{senha}}",
  "Role": {{role}}
}
###

PUT {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Accept: application/json
Content-Type: application/json


{
  "Nome": "{{nome}}",
  "Email": "{{email}}",
  "SenhaHash": "{{senha}}",
  "Role": {{role}}
}
###

DELETE {{PiscinaPerfeita.Api_HostAddress}}/{{query}}
Authorization: Bearer {{token}}
###