// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PiscinaPerfeita.Api.Data;

#nullable disable

namespace PiscinaPerfeita.Api.Migrations
{
    [DbContext(typeof(PiscinaPerfeitaContext))]
    [Migration("20260620225425_EstadoInicialBanco")]
    partial class EstadoInicialBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "piscina-perfeita", "tipo_revestimento_enum", new[] { "Vinil", "Alvenaria", "Fibra de vidro", "Pastilhas", "Porcelanato/Ceramica", "Pedras naturais" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "piscina-perfeita", "tipo_tratamento_enum", new[] { "Quimico tradicional", "Salinizacao", "Ozonio", "Luz ultravioleta" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Analise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Alcalinidade")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CloroLivre")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("DataAnalise")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal?>("Ph")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PiscinaId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<decimal>>("Temperatura")
                        .HasColumnType("numeric[]");

                    b.HasKey("Id");

                    b.HasIndex("PiscinaId");

                    b.ToTable("Analises", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("PiscinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("QuantidadeAtual")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PiscinaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Estoque", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PiscinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PiscinaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MovimentacoesEstoque", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Piscina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ProfundidadeMedia")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VolumeLitros")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Piscinas", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Produtos", "piscina-perfeita");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Senhahash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senhahash");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Analise", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", "Piscina")
                        .WithMany("Analises")
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piscina");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Estoque", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", "Piscina")
                        .WithMany("Estoques")
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiscinaPerfeita.Api.Models.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piscina");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Piscina", "Piscina")
                        .WithMany("MovimentacoesEstoques")
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiscinaPerfeita.Api.Models.Produto", "Produto")
                        .WithMany("MovimentacoesEstoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piscina");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Piscina", b =>
                {
                    b.HasOne("PiscinaPerfeita.Api.Models.Usuario", "Usuario")
                        .WithMany("Piscinas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Piscina", b =>
                {
                    b.Navigation("Analises");

                    b.Navigation("Estoques");

                    b.Navigation("MovimentacoesEstoques");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Produto", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("MovimentacoesEstoques");
                });

            modelBuilder.Entity("PiscinaPerfeita.Api.Models.Usuario", b =>
                {
                    b.Navigation("Piscinas");
                });
#pragma warning restore 612, 618
        }
    }
}
